title: testing
description: testing
theme: just-the-docs

url: https://visualizela.github.io/visualizelacourse

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME
